// Generated by https://quicktype.io

export interface TopLevel {
  users:    User[];
  products: Product[];
}

export interface Product {
  id:                number;
  nombre:            string;
  precio:            string;
  peso:              string;
  fecha_publicacion: string;
  fecha_caducidad:   string;
}

export interface User {
  id:      number;
  usuario: string;
  email:   string;
}
